/**
 * ============================================
 * QUESTION MODEL - Stores Interview Questions
 * ============================================
 * 
 * These are the questions that AI generates based on
 * the user's resume. Each question is personalized!
 */

const mongoose = require('mongoose');

const questionSchema = new mongoose.Schema({
    // Which interview session this question belongs to
    sessionId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'InterviewSession'
    },

    // Which resume was used to generate this question
    resumeId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Resume'
    },

    // The actual question text
    questionText: {
        type: String,
        required: true
    },

    // Type of question
    category: {
        type: String,
        enum: ['technical', 'behavioral', 'situational', 'project', 'general'],
        required: true
    },

    // Resume context - why this question was asked
    // Example: "Based on your 3 years of React experience"
    basedOn: {
        type: String
    },

    // Which skill from resume this relates to
    relatedSkill: {
        type: String
    },

    // Which job experience this relates to
    relatedExperience: {
        type: String
    },

    // Key points a good answer should include
    expectedKeyPoints: [String],

    // How hard is this question
    difficultyLevel: {
        type: String,
        enum: ['easy', 'medium', 'hard'],
        default: 'medium'
    },

    // Time allowed to answer (in seconds)
    timeLimit: {
        type: Number,
        default: 120  // 2 minutes
    },

    // Hint for the candidate
    tips: String,

    // Was this generated by AI or manually added?
    isAIGenerated: {
        type: Boolean,
        default: true
    }
}, { timestamps: true });

module.exports = mongoose.model('Question', questionSchema);
